drop table if exists persons;
drop table if exists nationalities;
drop table if exists places;

create table nationalities (
  id int not null generated by default as identity,
  name varchar(45) not null,
  primary key (id)
);

create table places (
  id int not null,
  name varchar(45) not null,
  primary key (id)
);

create table persons (
  id int not null generated by default as identity,
  name varchar(45) not null,
  cpf varchar(45) not null,
  email varchar(45) not null,
  birth_place_id int not null default 0,
  nationality_id int not null default 0,
  sex int not null default 0,
  birth_date date not null,
  primary key (id),
  constraint idx_persons_cpf
    unique (cpf),
  constraint email_UNIQUE
    unique (email)
);

ALTER TABLE persons
  add foreign key (nationality_id)
    references nationalities (id) on delete no action on update no action;

ALTER TABLE persons
   add foreign key (birth_place_id)
    references places (id) on delete no action on update no action;
